# -*- coding: utf-8 -*-
"""KevinKangethe_02-Add_GeoJSON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NoH6dWqv_IKHIgiqL03qe5R6atGWAv9v

## 02 — Adding a GeoJSON Layer

In the last lesson we added individual markers — one Python object per feature. That approach breaks down fast: loading 500 city points means 500 `Marker` calls.

**GeoJSON layers** solve this. ipyleaflet's `GeoJSON` class takes a whole FeatureCollection and renders every feature in one shot — points, lines, and polygons together.

## Coordinate Order: GeoJSON vs ipyleaflet

Before writing any code, the most important thing to know:

| Where | Order | Example |
|---|---|---|
| GeoJSON | `[longitude, latitude]` | `[-98.49, 33.91]` |
| ipyleaflet `Map`/`Marker` | `(latitude, longitude)` | `(33.91, -98.49)` |

GeoJSON follows the mathematical `(x, y)` convention — longitude is the x-axis. ipyleaflet's `Map` and `Marker` use the geographic convention — latitude first.

The `GeoJSON` layer class reads a GeoJSON dict directly, so its coordinates stay in GeoJSON order `[lon, lat]`. You do not need to swap them.

## Adding a GeoJSON Layer from a Dict

The simplest case: pass a GeoJSON dict straight to `GeoJSON()` and add it to the map.
"""

from ipyleaflet import Map, GeoJSON

WICHITA_FALLS = (33.9137, -98.4934)  # (lat, lon) — ipyleaflet order

# A minimal FeatureCollection with two points
data = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [-98.4934, 33.9137]},  # [lon, lat]
            "properties": {"name": "City Hall"}
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [-98.5187, 33.8956]},
            "properties": {"name": "Midwestern State University"}
        }
    ]
}

m = Map(center=WICHITA_FALLS, zoom=12)
layer = GeoJSON(data=data)
m.add(layer)
m

"""## Loading GeoJSON from a File

In practice, GeoJSON lives in a file. Use Python's `json` module to load it, then pass the result to `GeoJSON(data=...)`.
"""

import json
from ipyleaflet import Map, GeoJSON

with open("data/wichita_falls.geojson") as f:
    wichita_data = json.load(f)

# wichita_data is now a plain Python dict — same structure as above
print(type(wichita_data))
print(f"{len(wichita_data['features'])} features")

m = Map(center=WICHITA_FALLS, zoom=12)
layer = GeoJSON(data=wichita_data)
m.add(layer)
m

"""One `GeoJSON()` call rendered all six features — points, a line, and a polygon — from the file.

## Inspecting the Features

Before displaying data, it is worth checking what geometry types are present. The `type` key on each feature's `geometry` tells you.
"""

for feature in wichita_data["features"]:
    name = feature["properties"]["name"]
    geom_type = feature["geometry"]["type"]
    print(f"{geom_type:12}  {name}")

"""## Multiple Layers on One Map

You can call `m.add()` multiple times to stack layers. Each `GeoJSON` object is its own layer — useful when you want to control them independently later.
"""

from ipyleaflet import Map, GeoJSON

# Split the features by geometry type
points = {"type": "FeatureCollection", "features": [
    f for f in wichita_data["features"] if f["geometry"]["type"] == "Point"
]}
lines = {"type": "FeatureCollection", "features": [
    f for f in wichita_data["features"] if f["geometry"]["type"] == "LineString"
]}
polygons = {"type": "FeatureCollection", "features": [
    f for f in wichita_data["features"] if f["geometry"]["type"] == "Polygon"
]}

m = Map(center=WICHITA_FALLS, zoom=12)
m.add(GeoJSON(data=points))
m.add(GeoJSON(data=lines))
m.add(GeoJSON(data=polygons))
m

"""## Removing a Layer

Keep a reference to the layer object and call `m.remove()` to take it off the map.
"""

from ipyleaflet import Map, GeoJSON

m = Map(center=WICHITA_FALLS, zoom=12)

point_layer = GeoJSON(data=points)
poly_layer  = GeoJSON(data=polygons)

m.add(point_layer)
m.add(poly_layer)

# Remove just the polygon layer — point layer stays
m.remove(poly_layer)

m

"""## Exercise A

Load `data/meteorites.geojson` and display all features as a single `GeoJSON` layer on a world-scale map (`center=(20, 0)`, `zoom=2`).
"""

import json
from ipyleaflet import Map, GeoJSON

with open("meteorites.geojson") as f:
    meteorites = json.load(f)

# Display all meteorite features as a single GeoJSON layer on a world map
# center=(20, 0), zoom=2
# Your code here
m = Map(center=(20, 0), zoom=2)

layer = GeoJSON(data=meteorites)
m.add(layer)

m

"""## Exercise B

Using `data/wichita_falls.geojson`:

1. Print the count of features for each geometry type
2. Display all features on one map with each geometry type as a **separate named layer**
"""

import json
from ipyleaflet import Map, GeoJSON

with open("wichita_falls.geojson") as f:
    features = json.load(f)["features"]

# Count features per geometry type, then display all on one map with each type as a separate named layer
# Your code here
# ---- 1. Count geometry types ----
counts = {}

for f in features:
    gtype = f["geometry"]["type"]
    counts[gtype] = counts.get(gtype, 0) + 1

for k, v in counts.items():
    print(k, ":", v)

# ---- 2. Group by type ----
groups = {}
for f in features:
    gtype = f["geometry"]["type"]
    groups.setdefault(gtype, []).append(f)

# ---- 3. Create map ----
m = Map(center=(33.9137, -98.4934), zoom=12)

for gtype, feats in groups.items():
    layer = GeoJSON(
        data={"type": "FeatureCollection", "features": feats},
        name=gtype
    )
    m.add(layer)

m

"""---

## Check Your Understanding

Load `data/wichita_falls.geojson` and display **only the polygon features** on a map. Print the name of each polygon feature before displaying the map.

```python
# your answer here
```
"""

import json
from ipyleaflet import Map, GeoJSON

with open("wichita_falls.geojson") as f:
    data = json.load(f)

polygons = []

for f in data["features"]:
    if f["geometry"]["type"] == "Polygon":
        print(f["properties"]["name"])
        polygons.append(f)

m = Map(center=(33.9137, -98.4934), zoom=12)

poly_layer = GeoJSON(
    data={"type": "FeatureCollection", "features": polygons}
)

m.add(poly_layer)

m

"""## Next

In [03 — Map Controls](./03-Map_Control.ipynb), we add UI elements — layer toggles, a scale bar, fullscreen, and a minimap — to make the map more usable.
"""